version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: health-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: health_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - health-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: health-backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:admin123@postgres:5432/health_app"
      JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
      JWT_EXPIRATION: "7d"
      PORT: 3001
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - health-network

networks:
  health-network:
    driver: bridge

volumes:
  postgres_data:
